image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off  # будем использовать свой скрипт сборки

install:
  - java -jar ./artifacts/app-mbank.jar &

build_script:
  - chmod +x  ./gradlew
  - ./gradlew test --info
